version: '2'
services:
    jenkins:
        image: walterfan-jenkins
        container_name: jenkins
        restart: always
        ports:
            - 1978:8080
        volumes:
            - ./data/jenkins:/var/jenkins_home
            - ../..:/workspace
