version: '3.8'

services:
  # Nginx reverse proxy with HTTPS
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - keycloak
    networks:
      - keycloak-network

  # Keycloak identity provider with MySQL
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_PROXY=edge
      - KC_HOSTNAME=keycloak.fanyamin.com
      - KC_HOSTNAME_STRICT_HTTPS=true
      # MySQL configuration
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://keycloak-db:3306/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      # Health check options
      - KC_HEALTH_ENABLED=true
    command: ["start"]
    depends_on:
      - keycloak-db
    expose:
      - "8080"
    networks:
      - keycloak-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5

  # MySQL database for Keycloak
  keycloak-db:
    image: mysql:8.0
    container_name: keycloak-db
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloak
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - keycloak-db-data:/var/lib/mysql
    networks:
      - keycloak-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  keycloak-db-data:

networks:
  keycloak-network:
    driver: bridge