apiVersion: v1
kind: Service
metadata:
  name: hello-node-svc
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31111
  selector:
    project: hello-node
    
