version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "1980:80"
            #- "3000:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            #- "./etc/ssl:/etc/ssl"
            - "./web:/web"
            - ./logs/nginx-error.log:/var/log/nginx/error.log
            - ./logs/nginx-access.log:/var/log/nginx/access.log
            - .:/workspace
        depends_on:
            - "php"
            - "mysqldb"
        links:
            - php
    php:
        image: walterfan-php-fpm
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ./web:/web

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "1981:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: always
        depends_on:
            - "mysqldb"
        links:
            - "mysqldb"
    mysqldb:
        image: mysql
        container_name: mysql
        restart: always
        environment:
            - MYSQL_DATABASE=test
            - MYSQL_ROOT_PASSWORD=pass1234
            - MYSQL_USER=walter
            - MYSQL_PASSWORD=pass1234
        ports:
            - 3306:3306
        volumes:
            - ./data/db/mysql:/var/lib/mysql


