version: "3"
services:
    redis-stack:
        image: redis/redis-stack:latest
        container_name: redis-stack
        volumes:
            - ./local-data/:/data
        expose:
            - 6379
            - 8001
        ports:
            - "6379:6379"
            - "8001:8001"
        environment:
            - PATH=./bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin